version: '3.7'
services:
  restapi_web:
    container_name: restapi_web
    image: transluciddata/restapi_web
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: Dockerfile